### ISSUE TITLE
error: failed to download `build-helper v0.1.1`

### ISSUE THREAD

**Issue by skysegbr** [huwwynnjones/oci_rs#10]
Hello everyone, I can't solve this.

[dependencies]
oci_rs = "0.8.0"
rustc 1.40.0 (73528e339 2019-12-16)

**Comment by huwwynnjones** [comment]
This is a bit strange. I just create a test program and added oci_rs as a dependency. I am using 1.40.0 as well. It downloaded everything just fine. Do you still have the issue? maybe it was a network glitch?

**Comment by skysegbr** [comment]
Hello, in fact the error occurred due to not having lib oci.lib in the path \ .rustup \ toolchains \ stable-i686-pc-windows-msvc \ lib \ rustlib \ i686-pc-windows-msvc \ lib.
This solved the problem.
thanks.
By the way, where I can take questions beyond the documentation?

**Comment by huwwynnjones** [comment]
ok good. glad that it worked itself out. if you have questions, then just raise a new issue and i will keep an eye out for them and try to help as soon as i can.
