### ISSUE TITLE
Use opaque structs over empty enums in FFI

### ISSUE THREAD

**Issue by senojj** [huwwynnjones/oci_rs#8]
Currently, you are using empty enums to represent the OCI opaque handle structs, such as Env. According to official Rust documentation, this is a bad idea.

From the Rust nomicon:
"Notice that it is a really bad idea to use an empty enum as FFI type. The compiler relies on empty enums being uninhabited, so handling values of type &Empty is a huge footgun and can lead to buggy program behavior (by triggering undefined behavior)."

See here: https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs

**Comment by huwwynnjones** [comment]
Interesting. Thanks for pointing this out. I copied my approach from somewhere else, although it escapes me where from exactly at the moment. I will look into changing this.

**Comment by huwwynnjones** [comment]
Swapped them all out, no change in tests. Will commit at some point. Thanks!

**Comment by huwwynnjones** [comment]
Committed now.
